#!/usr/bin/env bash
# Installs Nginx with following configurations:
#+    Listens on port 80
#+    Returns page containing "Holberton School" when queried
#++    at root with curl GET request

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
service nginx restart
