#!/usr/bin/env bash
#does the following:
#	create file /var/run/holbertonscript.pid containing script PID.
#	displays "To infinity and beyond" indefinitely
#	displays "I hate the kill command" upon receiving SIGTERM
#	displays "Y U no love me?!" upon receiving SIGINT
#	deletes the file /var/run/holbertonscript.pid and terminates upon
#	receiving SIGQUIT or SIGTERM.

terminator() {
	rm /var/run/holbertonscript.pid
	exit
}

echo "$$" > /var/run/holbertonscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
