#!/usr/bin/env bash
#displays contents of the file `/etc/passwd`
#	only displays the username, user id, and user home directory path

while read passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
